//*!!Code automatically generated by 'ROBOTC' configuration wizard           !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2013                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     flashFileDemo.c                                              */
/*    Author:     James Pearman                                                */
/*    Created:    7 Jan 2014                                                   */
/*                                                                             */
/*    Revisions:                                                               */
/*                V1.00  8 Jan 2014 - Initial release                          */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX cortex        */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

#include <FlashLib.h>

static char tmpData[1024];

void
WaitForKey()
{
    while( nLCDButtons == 0 )
        wait1Msec(5);
    while( nLCDButtons != 0 )
        wait1Msec(5);
}

task main()
{
    int   i;
    unsigned char *data;
    int           datalength;
    char    lastname[16];

    bLCDBacklight = true;

    writeDebugStreamLine("wait");
    wait1Msec(1000);

    // create some test data
    for(i=0;i<1024;i++)
        tmpData[i] = i;


    while(1)
        {
        // use LCD as trigger to save a file
        displayLCDString(0, 0, "Hit button to   ");
        displayLCDString(1, 0, "continue...     ");

        WaitForKey();

        clearLCDLine(0);
        displayLCDString(1, 0, "save a file ... ");

        // write a file
        if( RCFS_AddFile( tmpData, 1024 ) == RCFS_ERROR )
            writeDebugStreamLine("File write error");

        // This would save a named file
        //if( RCFS_AddFile( tmpData, 1024, "myfile" ) == RCFS_ERROR )
        //    writeDebugStreamLine("File write error");

        // dump directory
        RCFS_ReadVTOC();

        // Get the name of the last file written
        RCFS_GetLastFilename( lastname, 16 );

        // Get a pointer to the data in that last file
        // Pass the address of the data pointer (we call that a handle)
        if( RCFS_GetFile( lastname, &data, &datalength ) == RCFS_SUCCESS )
            {
            writeDebugStreamLine("last file written was %s", &lastname[0] );
            writeDebugStreamLine("data ptr is %08X", data );
            writeDebugStreamLine("length is %08X", datalength );
            writeDebugStreamLine("the file starts like this ...");
            for(i=0;i<16;i++)
                writeDebugStream("%02X ", *(data+i) );
            writeDebugStreamLine("");
            }

        wait1Msec(500);
        }
}
